---
#-------------------------------
# Site Settings
title: Prokop 'Ash' Hanžl
logo: # You can add own logo. For example "/images/logo.png".
description: Multipurpose Jekyll Blog Theme

#-------------------------------
# Author Global Settings
author:
    author__name: Prokop 'Ash' Hanžl
    author__bio: Hi! My name's Prokop Hanžl, but I mostly go by Ash on the internet. I study linguistics and phonetics at Charles University in Prague, I love making music and traveling, and I dabble in coding.
    author__avatar: /images/ash.jpg

#-------------------------------
# Navigation Settings
menu__settings:
    menu__items:
        - title: "Home"
          url: "/"
        - title: "About Me"
          url: "/about/"
        # - title: 'Pages'
        #   submenu:
        #   - url: '/authors/'
        #     title: 'Authors'
        #   - url: '/elements/'
        #     title: 'Elements'
        - title: "Contact"
          url: "/contact/"

#-------------------------------
# Hero Settings
hero:
    hero__title: Hi! I'm Prokop. I study linguistics and phonetics, I love making music and traveling, and I dabble in coding.

#-------------------------------
# Blog Settings
blog:
    blog__title: Blog
    blog__description: My occasional blog posts.

#-------------------------------
# Recommended Tag Settings
tag:
    enable: false
    tag__title:
    tag__name:

#-------------------------------
# Newsletter Settings
mailchimp:
    enable: false
    mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__title: Get interesting news
    mailchimp__description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
    mailchimp__input__text: Your Email Address...
    mailchimp__button__text: Subscribe
    mailchimp__background__image: "/images/110.jpg"

#-------------------------------
# Footer Settings

# Footer Navigation
footer__menu__settings:
    menu__items:
        - title: "Home"
          url: "/"
        - title: "About Me"
          url: "/about/"
        - title: "Contact"
          url: "/contact/"
        # - title: "Authors"
        #   url: "/authors/"
        # - title: "Elements"
        #   url: "/elements/"

# Social Links
social:
    - { icon: "", color: "#0a66c2", name: LinkedIn, link: "https://linkedin.com/in/prokop-hanzl" }
    - { icon: "", color: "#000", name: GitHub, link: "https://github.com/prokophanzl" }
    - { icon: "", color: "#f00", name: Youtube, link: "https://youtube.com/@minutelinguistics" }
    - { icon: "", color: "#1db954", name: Spotify, link: "https://open.spotify.com/artist/4ki6RhFsTwbGQk7zOisJyD" }

#-------------------------------
# Contact Settings
contact:
    email: # Add your email for contant form

# NOTE
# Dann theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Comment Section (Disqus)
disqus:
    enable: false
    disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test

#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id
